### ISSUE TITLE
Where are the JSON files stored?

### ISSUE THREAD

**Issue by antfuentes87** [SL-x-TnT/GoManager#4]
@SL-x-TnT I am wondering where the actual JSON files are stored? Because I am wondering if it is possible to just create the JSON file, put it in the folder where the program stores them and not have to actually use the import function in the program itself.  Hope that makes sense, and thanks!

**Comment by SL-x-TnT** [comment]
data.json.gz in the newest versions >1.2.4
data.json in the older versions

It'll be painful to add a manual config to an account. Your best bet would be
(Highlight accounts) Right click -> Settings -> Import Config

**Comment by antfuentes87** [comment]
Well I am using Python to generate the data.json, so it will be easy. Only part I don't like is the IDs that are counting up through the entire data.json, but it should be doable. Thanks for letting know where it was at!

**Comment by selfantasy** [comment]
How to edit the .gz in win10 ?
Many thanks.
Plus question: How does "setting ->Evolve ->Set Requied Pokemon" work?
I key in Zubat or Dragonite both invalid. Should it be a serial number or before/after evolve pokemon name?

**Comment by antfuentes87** [comment]
A .GZ extension is a type of compression, so I just used [](http://www.7-zip.org) to uncompress it. Then once you do that, you will see the JSON file inside. Hope this helps!

**Comment by SL-x-TnT** [comment]
@selfantasy It's the number of pokemon that can evolve before it'll evolve everything.
