### ISSUE TITLE
error after every 30 mins of using the bot

### ISSUE THREAD

**Issue by vike02** [SL-x-TnT/GoManager#8]
hai i am a big fan of gomanager since the update of 1.3.3....but i noticed that after i use the app for about 30 mins or so the is a msg saing that i was permbanned but not to worry i wasnt.....when i restart the app it works fine please help

**Comment by Lbniese** [comment]
Sounds like a proxy error.

**Comment by SL-x-TnT** [comment]
Your computer's time is incorrect.

**Comment by vike02** [comment]
the time is correct......correct me if iam wrong...if it is a proxy error it shoudnt open right???or if it is a ip ban i shouldn't be able to catch any pokemons for atleast an hour.....i dont have both.....pls any other suggetions

**Comment by vike02** [comment]
and when i use the older version it work perfect with the same config.....the older version is 1.2.7.....

**Comment by SL-x-TnT** [comment]
The main difference between those 2 versions is that it uses your system's time to determine when a session expires. Constant logging in or getting false positives with Account ban are side effects of time being too far ahead or too far behind.

**Comment by vike02** [comment]
thanks a lot the computer time was right but it was a month behind.....i corrected it...now working like a piece of cake.....but now i have a new prob....iam in level 29 and my xp is aroun 32000 but the bot says it is 332000 i tried closing and opening the bot ,even deleted the acount and again impored it.....still no luck please help

**Comment by SL-x-TnT** [comment]
Exp gained?
Exp required?

**Comment by vike02** [comment]
the experiencer gained is working wrong...it is still around 50 % but my real one is aroun 15 %....please help

**Comment by vike02** [comment]
and why is there any new updates available?????

**Comment by SL-x-TnT** [comment]
If you want to fix it, in the item templates ...
Get the level experience. Grab the next level and current level. Calculate it from that. If you don't, it's wrong.

There's no updates because I'm recoding the API, and making it close source.

**Comment by khairulpetrcech** [comment]
Do u plan to release the next bot with the close API u making?

If so,will the API patch the problem exist in rocketAPI(broken API,whivh niantic can detect easily)?

**Comment by SL-x-TnT** [comment]
Recoded version should mimic the app a lot better. Not perfect, but nothing is.

**Comment by vike02** [comment]
why making it a closed source????

**Comment by khairulpetrcech** [comment]
Sorry to ask if this is not the correct thread..but i do hope u could answer this simple question..what iv calculator u use to calculate it ? Because the result different from the website that i use..

**Comment by vike02** [comment]
can u please explaing how to fix the experience error in detail please...

**Comment by SL-x-TnT** [comment]
The IV % is calculated how FeroxRev did it. Uses CP instead of IV values.

```
            get
            {
                if (Stats == null || LevelSettings == null || Stats.Level == 0)
                {
                    return "??/??";
                }

                if(Stats.Level == 40)
                {
                    return "N/A";
                }

                int currentLevelExp = LevelSettings.RequiredExperience[Stats.Level - 1];

                long currentExp = Stats.Experience - currentLevelExp;
                long required = LevelSettings.RequiredExperience[Stats.Level] - currentLevelExp;

                double ratio = 0;

                if (required != 0)
                {
                    ratio = (double)currentExp / required * 100;
                }

                return String.Format("{0}/{1} ({2:0.00}%)", currentExp, required, ratio);
            }
```

**Comment by vike02** [comment]
PLEASE HELP ME WITH THE EXPERIENCE ERROR....IT IS EXACTY 100000 HIGHER THAN THE ORIGINAL ONE....AND WHEN WILL YOU BE RELEASING THE NEW BOT WITH THE RECODED API?????

**Comment by SL-x-TnT** [comment]
I showed you how I calculated it in my next version, and I won't give an ETA on the release.

**Comment by vike02** [comment]
eta???
